-- Generated by the database client.
BEGIN;

-- =========================================
-- ARTIGOS (nome UNIQUE → empresa_id + nome)
-- =========================================
[*]
ALTER TABLE artigos DROP CONSTRAINT artigos_nome_key;

CREATE UNIQUE INDEX artigos_empresa_id_nome_unique
ON artigos (empresa_id, nome)
WHERE deleted_at IS NULL;


-- =========================================
-- ARTIGOS_TIPO (descricao UNIQUE → empresa_id + descricao)
-- =========================================
[*]
ALTER TABLE artigos_tipo DROP CONSTRAINT artigos_tipo_descricao_key;

CREATE UNIQUE INDEX artigos_tipo_empresa_id_descricao_unique
ON artigos_tipo (empresa_id, descricao)
WHERE deleted_at IS NULL;


-- =========================================
-- CLIENTES (nif UNIQUE → empresa_id + nif)
-- =========================================
[*]
ALTER TABLE clientes DROP CONSTRAINT clientes_nif_key;

CREATE UNIQUE INDEX clientes_empresa_id_nif_unique
ON clientes (empresa_id, nif)
WHERE deleted_at IS NULL;


-- =========================================
-- MOEDAS (simbol UNIQUE → empresa_id + simbol)
-- =========================================
[*]
ALTER TABLE moedas DROP CONSTRAINT moedas_simbol_key;

CREATE UNIQUE INDEX moedas_empresa_id_simbol_unique
ON moedas (empresa_id, simbol)
WHERE deleted_at IS NULL;


-- =========================================
-- PERMISSOES (nome UNIQUE → empresa_id + nome)
-- =========================================
[*]
ALTER TABLE permissoes DROP CONSTRAINT permissoes_nome_key;

CREATE UNIQUE INDEX permissoes_empresa_id_nome_unique
ON permissoes (empresa_id, nome)
WHERE deleted_at IS NULL;


-- =========================================
-- ROLES (nome UNIQUE → empresa_id + nome)
-- =========================================

-- só executa se existir constraint antiga
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'roles_nome_key'
    ) THEN
        ALTER TABLE roles DROP CONSTRAINT roles_nome_key;
    END IF;
END $$;
[*]
ALTER TABLE roles DROP CONSTRAINT roles_nome_key;
CREATE UNIQUE INDEX roles_empresa_id_nome_unique
ON roles (empresa_id, nome)
WHERE deleted_at IS NULL;


-- =========================================
-- FUNCIONARIOS (user_id UNIQUE → empresa_id + user_id)
-- =========================================
[*]
ALTER TABLE funcionarios DROP CONSTRAINT funcionarios_user_id_key;

CREATE UNIQUE INDEX funcionarios_empresa_id_user_id_unique
ON funcionarios (empresa_id, user_id)
WHERE deleted_at IS NULL;


-- =========================================
-- NOTA: NÃO ALTERAR
-- =========================================

-- empresas → deve continuar global UNIQUE
-- users → deve continuar global UNIQUE
-- documento_fiscal → não tem UNIQUE relevante
-- tabelas pivot → não precisam


COMMIT;



TRUNCATE TABLE
  public.artigo_itens,
  public.documentos_fiscal,
  public.artigos,
  public.artigos_tipo,
  public.clientes,
  public.pagamentos_tipo,
  public.role_permissoes,
  public.user_permissoes,
  public.user_roles,
  public.permissoes,
  public.roles,
  public.funcionarios,
  public.users,
  public.moedas,
  public.empresas
RESTART IDENTITY CASCADE;


TRUNCATE TABLE auth.users CASCADE;
